# ROS2 Foxy environment
source /opt/ros/foxy/setup.bash

if [ -f /home/ros/ws_ros2/install/setup.bash ]; then
    source /home/ros/ws_ros2/install/setup.bash
fi

export ROS_DOMAIN_ID=0
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export CYCLONEDDS_URI=file:///home/ros/cyclonedds.xml

alias cws='cd /home/ros/ws_ros2'
alias cb='cd /home/ros/ws_ros2 && colcon build --symlink-install'
alias cs='source /home/ros/ws_ros2/install/setup.bash'
alias rt='ros2 topic list'
alias rn='ros2 node list'
alias re='ros2 topic echo'
alias go2ping='ping -c 4 192.168.123.161 && ping -c 4 192.168.123.18'

echo "ROS2 Foxy Go2 container loaded."
echo "ROS_DISTRO=$ROS_DISTRO"
echo "RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION"
echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID"