#!/usr/bin/env bash

set -e

SDK_REPO_URL="https://github.com/unitreerobotics/unitree_sdk2.git"
SDK_REF="${SDK_REF:-}"
WORKSPACE_DIR="${WORKSPACE_DIR:-/home/ros/ws_humble}"
SDK_SRC_DIR="${SDK_SRC_DIR:-${WORKSPACE_DIR}/vendor/unitree_sdk2}"
INSTALL_PREFIX="${INSTALL_PREFIX:-/opt/unitree_robotics}"
ENV_HOOK="${INSTALL_PREFIX}/setup.sh"

echo "Unitree SDK2 setup"
echo "Workspace:       ${WORKSPACE_DIR}"
echo "SDK source dir:  ${SDK_SRC_DIR}"
echo "Install prefix:  ${INSTALL_PREFIX}"

echo "Checking system packages..."

sudo apt-get update
sudo apt-get install -y \
    git \
    cmake \
    g++ \
    make \
    build-essential \
    libyaml-cpp-dev \
    libeigen3-dev \
    libboost-all-dev \
    libspdlog-dev \
    libfmt-dev

mkdir -p "${WORKSPACE_DIR}"
mkdir -p "$(dirname "${SDK_SRC_DIR}")"

if [ ! -d "${SDK_SRC_DIR}/.git" ]; then
    echo "Cloning unitree_sdk2..."
    git clone "${SDK_REPO_URL}" "${SDK_SRC_DIR}"
else
    echo "unitree_sdk2 already exists. Pulling latest changes..."
    cd "${SDK_SRC_DIR}"
    git pull
fi

if [ -n "${SDK_REF}" ]; then
    echo "Checking out unitree_sdk2 ref: ${SDK_REF}"
    cd "${SDK_SRC_DIR}"
    git fetch --all --tags
    git checkout "${SDK_REF}"
fi

echo "Building unitree_sdk2..."

cd "${SDK_SRC_DIR}"
rm -rf build
mkdir -p build
cd build

cmake .. -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}"
make -j"$(nproc)"

echo "Installing unitree_sdk2 to ${INSTALL_PREFIX}..."
sudo make install

echo "Writing persistent SDK environment hook..."

sudo tee "${ENV_HOOK}" > /dev/null <<EOF
#!/usr/bin/env bash

# Generated by setup_unitree_sdk2.sh
export UNITREE_SDK2_INSTALL_PREFIX=${INSTALL_PREFIX}
export CMAKE_PREFIX_PATH=${INSTALL_PREFIX}:\${CMAKE_PREFIX_PATH}
export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:\${LD_LIBRARY_PATH}
EOF

sudo chmod 755 "${ENV_HOOK}"

export CMAKE_PREFIX_PATH="${INSTALL_PREFIX}:${CMAKE_PREFIX_PATH}"
export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}"

echo "Verifying installation..."

if [ -d "${INSTALL_PREFIX}/include" ]; then
    echo "Found include directory: ${INSTALL_PREFIX}/include"
else
    echo "Warning: include directory not found."
fi

if [ -d "${INSTALL_PREFIX}/lib" ]; then
    echo "Found library directory: ${INSTALL_PREFIX}/lib"
else
    echo "Warning: library directory not found."
fi

echo "Unitree SDK2 setup complete."
echo ""
echo "Environment hook written to ${ENV_HOOK}"
echo "New shells will pick it up automatically through the container entrypoint and bashrc."
echo ""
echo "Optional reproducibility hint:"
echo "SDK_REF=<tag-or-commit> /home/ros/tools/scripts/setup_unitree_sdk2.sh"
echo ""
echo "Useful checks:"
echo "ls ${INSTALL_PREFIX}"
echo "ls ${INSTALL_PREFIX}/include"
echo "ls ${INSTALL_PREFIX}/lib"
echo ""
