#!/usr/bin/env bash

set -e

SDK_REPO_URL="https://github.com/unitreerobotics/unitree_sdk2_python.git"
SDK_REF="${SDK_REF:-}"
WORKSPACE_DIR="${WORKSPACE_DIR:-/home/ros/ws_humble}"
SDK_SRC_DIR="${SDK_SRC_DIR:-${WORKSPACE_DIR}/vendor/unitree_sdk2_python}"
ENV_HOOK="${INSTALL_PREFIX:-/opt/unitree_robotics}/python_env.sh"

echo "Unitree SDK2 Python setup"
echo "Workspace:      ${WORKSPACE_DIR}"
echo "SDK source dir: ${SDK_SRC_DIR}"

sudo apt-get update
sudo apt-get install -y \
    git \
    python3-pip \
    python3-dev \
    cmake \
    build-essential

python3 -m pip install --upgrade pip setuptools wheel

mkdir -p "${WORKSPACE_DIR}"
mkdir -p "$(dirname "${SDK_SRC_DIR}")"

if [ ! -d "${SDK_SRC_DIR}/.git" ]; then
    echo "Cloning unitree_sdk2_python..."
    git clone "${SDK_REPO_URL}" "${SDK_SRC_DIR}"
else
    echo "unitree_sdk2_python already exists. Pulling latest changes..."
    cd "${SDK_SRC_DIR}"
    git pull
fi

if [ -n "${SDK_REF}" ]; then
    echo "Checking out unitree_sdk2_python ref: ${SDK_REF}"
    cd "${SDK_SRC_DIR}"
    git fetch --all --tags
    git checkout "${SDK_REF}"
fi

cd "${SDK_SRC_DIR}"

echo "Writing persistent Python environment hook..."
sudo tee "${ENV_HOOK}" > /dev/null <<EOF
#!/usr/bin/env bash

# Generated by setup_unitree_sdk2_python.sh
export UNITREE_SDK2_PYTHON_SRC=${SDK_SRC_DIR}
export PYTHONPATH=${SDK_SRC_DIR}:\${PYTHONPATH}
EOF

sudo chmod 755 "${ENV_HOOK}"

echo "Installing Python SDK in editable mode for the current container..."
pip3 install -e .

echo "Unitree SDK2 Python setup complete."
echo ""
echo "Environment hook written to ${ENV_HOOK}"
echo "New shells will add the SDK source to PYTHONPATH automatically."
echo ""
echo "Useful tests:"
echo "cd ${SDK_SRC_DIR}"
echo "python3 ./example/high_level/read_highstate.py <network_interface>"
echo "python3 ./example/high_level/sportmode_test.py <network_interface>"
echo ""
echo "Optional reproducibility hint:"
echo "SDK_REF=<tag-or-commit> /home/ros/tools/scripts/setup_unitree_sdk2_python.sh"
